### ISSUE TITLE
Small error in CDK Workshop Code?

### ISSUE THREAD

**Issue by RajivKYadav** [awsdocs/aws-cdk-guide#105]
I'm new to all things AWS so hopefully I am not raising an incorrect issue.  
Found a little error when trying out the code examples in the CDK Workshop.  Here is the code snipet from: cdk-workshop-stack.ts, which did not work for me:
new TableViewer(this, 'ViewHitCounter', {
      title: 'Hello Hits',
      table: helloWithCounter.table

This is what i modified it to, to make it work:

const viewer = new TableViewer(this, 'ViewHitCounter',{
      title: 'Hello Hits', 
      table: helloWithCounter.table

Maybe other more familiar programmers would find this trivial and be able to debug and fix quickly, however, it might save some novices like me a few hours (ok, several hours... ) of troubleshooting.... hope this helps.

**Comment by Jerry-AWS** [comment]
Hi @RajivKYadav, the CDK Workshop is actually in a separate repo from the Developer Guide. Would you be so kind as to file this over at https://github.com/aws-samples/aws-cdk-intro-workshop? (You could even make a PR, if you have time.)

**Comment by Jerry-AWS** [comment]
I see it! Thanks, closing this one; I'll make sure it's taken care of.
