### ISSUE TITLE
Code Pipeline example should be more step-by-step like other examples

### ISSUE THREAD

**Issue by Jerry-AWS** [awsdocs/aws-cdk-guide#107]
Got the following suggestion from a customer:

"This document lacks the step-by-step granularity that are in the Serverless & ECS examples. It would be great if the commands for adding directories and a Lambda example were included. aka the option to copy/paste in sequence to arrive at the expected outcome."

**Comment by nikhilbhoj** [comment]
I have created a Step-by-step example based on the official example on Codepipeline in my blog post.
https://nikhilbhojcloud.blogspot.com/2019/08/code-pipeline-using-aws-cdk-for-lambda.html 

Hope it may help.

**Comment by Jerry-AWS** [comment]
This is better than it was, and it now works, but could probably still use some love around explaining the code.

**Comment by Jerry-AWS** [comment]
The recent changes to this topic should cover this.
