### ISSUE TITLE
Use of stack props in Python

### ISSUE THREAD

**Issue by isubuz** [awsdocs/aws-cdk-guide#108]
The docs [here](https://docs.aws.amazon.com/cdk/latest/guide/stack_how_to_create_multiple_stacks.html) shows how to pass custom stack properties. 

Unfortunately, the same pattern isn't applicable in the Python side as only the following stack props are supported -

- env
- stack_name
- tags

The python docs for `core.Stack` does mention `props` in the constructor docs, however it's not actually defined in the constructor interface. What i am missing or is there an alternative way to pass stack props. 

P.S - I have seen the docs to pass the context vars. But looking to implement the JS StackProps pattern in Python

**Comment by Jerry-AWS** [comment]
@isubuz: I'm guessing you're trying something like this:
```python
class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:

        super().__init__(scope, id, **kwargs)

        if kwargs.get("enc"):
            s3.Bucket(self, "MyGroovyBucket",
                             encryption=s3.BucketEncryption.KMS_MANAGED)
        else:
            s3.Bucket(self, "MyGroovyBucket")
```
To get it to work with the CDK, you need to accept all the arguments a `Stack` could take, plus `enc`, but pass only the `Stack` arguments upward. The Python version of the CDK accepts what would be `props` (in TS/JS) via keyword-only arguments. So you might follow suit and write it like this:
```python
class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, *, 
        env=None, stack_name=None, tags=None, enc=False) -> None:

        super().__init__(scope, id, env=env, stack_name=stack_name, tags=tags)

        if enc:
            s3.Bucket(self, "MyGroovyBucket",
                             encryption=s3.BucketEncryption.KMS_MANAGED)
        else:
            s3.Bucket(self, "MyGroovyBucket")
```

You could do it with `**kwargs` as well, you just have to explicitly pull out the necessary values and pass them as individual arguments to the superclass `__init__` method:

```python
super().__init__(scope, id, env=kwargs.get("env"), 
    stack_name=kwargs.get("stack_name"),
    tags=kwargs.get("tags"))
```

I'll run it by the engineers, though. The `**kwargs` pattern is familiar to Python programmers and it would be nice to support it better. As a test, I modified `aws_cdk.core.Stack.__init__()` to accept `**kwargs` at the end of its parameter list and the first example worked fine. 

Besides its familiarity, I can see some benefits to supporting `**kwargs` (for example, if the parent class is a parameter and you don't know what props it accepts when you're writing the code).

I'm going to take a look at beefing up that help topic with a Python example as well, or maybe improve our "CDK in Other Languages" topic (https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html).

**Comment by isubuz** [comment]
@Jerry-AWS Thanks for the code snippets. I definitely vote for the `**kwargs` pattern. I am now following the below pattern with `Stack` subclass which passes the `Stack` args upwards.

```python
class Stack(core.Stack):
    def __init__(self, scope: core.Construct, name: str, **props) -> None:
        super().__init__(
            scope,
            name,
            env=props.get("env"),
            stack_name=props.get("stack_name"),
            tags=props.get("tags")
        )
```
Every stack now inherits from this Stack instead of `core.Stack`

**Comment by Jerry-AWS** [comment]
@isubuz Late last night I had a better idea: accept your own argument(s) as keyword or keyword-only, and everything else as `**kwargs`.  Then you can call the super init with `**kwargs` since they won't contain your argument(s). Have Python do the parameter-wrangling work for you!
```python
def __init__(self, scope, name, enc=False, **kwargs):
    super().__init__(scope, name, **kwargs)
    # etc
```

**Comment by Jerry-AWS** [comment]
I've raised this as a feature request over in the CDK project. https://github.com/aws/aws-cdk/issues/3731. I'll keep it open here though, since I want to recommend the above as the preferred way to handle the issue in the Developer Guide. (Using defined keyword arguments, rather than fishing stuff out of `**kwargs`, is a more discoverable API, so really, you should do that when you can.)

**Comment by isubuz** [comment]
Agree that the function definition with named arguments leads to discoverable API, IDE helpers etc. But IMO, this a good only for smaller number of stack params. In my case, for certain stacks i have more than 15 params  which really leads to quite long function definitions. I guess one must choose based on use cases.

**Comment by Jerry-AWS** [comment]
@isubuz Had a chat with one of the engineers and he told me he seemed to remember that this behavior was intentional, and was implemented because of the naming differences between TypeScript and Python. The current approach does have the benefit that when you translate TypeScript code to Python, if you don't translate the property names as Python expects them, you will get an error rather than your incorrectly-named property being ignored. The latter behavior could result in bugs that are difficult to track down, which I think is a good reason not to silently ignore unexpected props. I think what I'll do in this case is to add an explanation of how this works and what to do to the "CDK in Other languages" topic.

**Comment by Jerry-AWS** [comment]
@isubuz I'm about to publish a "How to Use the CDK in Python" topic that contains an explanation of the "right" way to do this. (It won't go live for a bit; we currently have a doc publishing freeze on because reasons.) So I'm going to close this and the corresponding issue in the CDK repo.

**Comment by DaviRolim** [comment]
> @isubuz I'm about to publish a "How to Use the CDK in Python" topic that contains an explanation of the "right" way to do this. (It won't go live for a bit; we currently have a doc publishing freeze on because reasons.) So I'm going to close this and the corresponding issue in the CDK repo.

The link for the post of "How to Use the CDK in Python"?

**Comment by Jerry-AWS** [comment]
https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-python.html#python-cdk-idioms (there's a paragraph in the Props section about it)

**Comment by Tavisca-Abhijeet-Choudhury** [comment]
Facing the same error even with using **kwargs in both the places (inside constructore __init__ and inside super as well). Very new to aws cdk. Can someone help?

```
class s3Stack2(Stack):
    
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        
        super().__init__(scope, construct_id, **kwargs)

        #########Logic for all the parameters

        access_control = kwargs.get("bucket_access_control", s3.BucketAccessControl.PRIVATE)
        auto_delete_objects = kwargs.get("auto_delete_objects", False)
        block_public_access = kwargs.get("blocking_public_access", s3.BlockPublicAccess.BLOCK_ALL)
        bucket_versioning = kwargs.get("bucket_versioning", False)
        s3_bucket_name = kwargs.get("bucket_name")
```
