### ISSUE TITLE
Viewing and Managing Context examples appear confused between text and examples

### ISSUE THREAD

**Issue by imajinos** [awsdocs/aws-cdk-guide#116]
I'm talking about https://docs.aws.amazon.com/cdk/latest/guide/context.html
.. where the text talks about linux AMI ids, but the example outputs are only about availability zones. 

eg., "To remove a context value, run cdk context --reset, specifying the value's corresponding key number. The following example removes the value that corresponds to the key value of 2 in the preceding example, which is the Amazon Linux AMI ID."

But preceding and following examples say nothing about AMI IDs.

**Comment by Jerry-AWS** [comment]
@imajinos Thanks for reporting this! I'll have a look, and you should see an update soon.

**Comment by Jerry-AWS** [comment]
@imajinos I've fixed this and it should be published on docs.aws.amazon.com in the next 24 hours.
