### ISSUE TITLE
Serverless Example is Confusing for Stack vs. Service

### ISSUE THREAD

**Issue by jkodroff** [awsdocs/aws-cdk-guide#122]
The output of `cdk init` creates:

- `bin/hello_world_service.ts`
- `lib/hello_world_service-stack.ts`

The code in the [Serverless example](https://docs.aws.amazon.com/cdk/latest/guide/serverless_example.html) seems to advocate putting the infrastructure that makes up the stack in `X_service.ts`, but the output of `cdk init` seems to steer the user to putting that code in `X_service-stack.ts`.

Not sure if this is a result of a typo in the docs or a recent change to the output of `cdk init`, but as a person working through the example, I'm finding the apparent conflict in what goes where confusing.

Hope this feedback is helpful!

**Comment by jkodroff** [comment]
BTW, as part of my learning here I'm happy to submit a PR on this, but the problem is that I don't know enough about CDK yet to understand best practices and the intent of the Serverless example code.

**Comment by Jerry-AWS** [comment]
@jkodroff I have an "anatomy of a CDK project" on the wishlist that should help clear some of this up. I think you might have found an error in the Serverless topic as well; I'll have a closer look at that. Thanks!

**Comment by jkodroff** [comment]
The anatomy content would be very valuable!  Thanks for the quick follow-up!
