### ISSUE TITLE
Document all options to the cli

### ISSUE THREAD

**Issue by jgondron** [awsdocs/aws-cdk-guide#123]
The tools page (https://docs.aws.amazon.com/cdk/latest/guide/tools.html) has the global options available to the cli, but not the specific command options. You get more options when running specific command help, ex: `cdk deploy help`. Would be nice to have all commands and their relevant options documented in a searchable guide, similar to AWS cli command reference https://docs.aws.amazon.com/cli/latest/index.html.

**Comment by Jerry-AWS** [comment]
This is a great idea. We can use a CLI topic.
