### ISSUE TITLE
Dev Guide, Tools section: Add more details about Bootstrapping your AWS environments

### ISSUE THREAD

**Issue by ccfife** [awsdocs/aws-cdk-guide#133]
Some customers are not entirely clear when to use the CDK Bootstrap command.  

"In the documentation however it is not clear that cdk bootstrap is not always required e.g. here https://docs.aws.amazon.com/cdk/latest/guide/tools.html. We understand that this is a new service/framework and some extra clarifications will be added as the time passes." - customer quote

For example, the documentation says: 

**Bootstrapping your AWS Environment**

> Before you can use the AWS CDK you must bootstrap your AWS environment to create the infrastructure that the AWS CDK CLI needs to deploy your AWS CDK app. Currently the bootstrap command creates only an Amazon S3 bucket.
> 
> You incur any charges for what the AWS CDK stores in the bucket. Because the AWS CDK does not remove any objects from the bucket, the bucket can accumulate objects as you use the AWS CDK. You can get rid of the bucket by deleting the CDKToolkit stack from your account. 

In reality, the CDKToolkit S3 bucket is only used when leveraging assets or when the generated stack is larger than 50kb.

**Comment by Jerry-AWS** [comment]
See also https://github.com/aws/aws-cdk/issues/4039

**Comment by Jerry-AWS** [comment]
See also https://github.com/aws/aws-cdk/issues/3684#issuecomment-586518441
