### ISSUE TITLE
Add dotnet commands for installing construct library modules in .NET

### ISSUE THREAD

**Issue by Jerry-AWS** [awsdocs/aws-cdk-guide#151]
This was not possible before GA of .NET support because dotnet won't install prerelease modules.

**Comment by whoiskevinrich** [comment]
Speaking as a pretty picky C# aws user, the [existing documentation](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-csharp.html) seems pretty complete for both the Visual Studio GUI and the dotnet CLI.

**Comment by Jerry-AWS** [comment]
Yes, guess I can close this now.  :-)
