### ISSUE TITLE
Make Getting Started less daunting

### ISSUE THREAD

**Issue by Jerry-AWS** [awsdocs/aws-cdk-guide#158]
Consider splitting the setup and hello world into separate topics. (They were originally.) Also had a customer request to include a way to verify that he had set his AWS credentials correctly.

**Comment by whoiskevinrich** [comment]
I'm not sure the interplay between this documentation and the [CDK Workshop](https://cdkworkshop.com/), but I've found that the workshop is a good resource for getting started and the API Reference works well for some of the more in-depth information.
