### ISSUE TITLE
Malformed CFN template in Getting Started

### ISSUE THREAD

**Issue by iliapolo** [awsdocs/aws-cdk-guide#164]
There is a malformed section of the CloudFormation template in the [Getting Started Guide](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html).

In the  *"Synthesizing an AWS CloudFormation Template"*:

![Screen Shot 2020-01-07 at 10 51 03 AM](https://user-images.githubusercontent.com/1428812/71881963-1a769800-313c-11ea-8ccd-26ea724102bd.png)

It seems to be OK in `Markdown` format on Github, but fails in the Wiki format.

**Comment by Jerry-AWS** [comment]
This was fixed by the Getting Started/Hello World revamp.
