### ISSUE TITLE
Misleading information about deploy operation in Getting Started

### ISSUE THREAD

**Issue by iliapolo** [awsdocs/aws-cdk-guide#165]
In the [Getting Started Guide](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html), under the **Deploying the Stack** section, it reads:

*"If your code includes **changes to your existing infrastructure**, the command displays information about those changes and requires you to confirm them before it deploys the changes"*

This statement is not accurate. The CDK requires approval **only** for security related changes. 

It lead me to believe that the CDK should have asked my approval before creating my bucket. When it didn't, it felt like a bug, which is not the best `hello-world` experience.

**Comment by Jerry-AWS** [comment]
That's a good find! Thanks; I'll fix that.

**Comment by Jerry-AWS** [comment]
That should be fixed now.
