### ISSUE TITLE
Typescript serverless example has unsupported nodejs runtime

### ISSUE THREAD

**Issue by devndive** [awsdocs/aws-cdk-guide#168]
As of January 6th, 2020 the creation of lambda function with the nodejs runtime 8.10 is deprecated.

Deploying the stack will yield the following error:
> The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.

See also [Runtime Support Policy](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html)

**Comment by Jerry-AWS** [comment]
Thanks! Merged your PR and am closing this issue.
