### ISSUE TITLE
NPM package cannot be installed.

### ISSUE THREAD

**Issue by jasonpmiller** [awsdocs/aws-cdk-guide#178]
$ sudo npm install -g aws-cdk
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/n/versions/node/10.16.0/lib
└── (empty)

npm ERR! Linux 4.14.165-133.209.amzn2.x86_64
npm ERR! argv "/usr/local/n/versions/node/10.16.0/bin/node" "/bin/npm" "install" "-g" "aws-cdk"
npm ERR! node v10.16.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/n/versions/node/10.16.0/lib/node_modules/.staging/semver-1515f545
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/n/versions/node/10.16.0/lib/node_modules/.staging/semver-1515f545' -> '/usr/local/n/versions/node/10.16.0/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/node_modules/semver'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/n/versions/node/10.16.0/lib/node_modules/.staging/semver-1515f545' -> '/usr/local/n/versions/node/10.16.0/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/node_modules/semver'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Jerry-AWS** [comment]
@jasonpmiller This doesn't seem like a problem with the CDK itself, it looks like something with your Node installation, but just in case, you might want to open an issue over in the CDK repo: https://github.com/aws/aws-cdk/issues

Closing this because it's not a AWS CDK Developer Guide issue.
