### ISSUE TITLE
Typo in Escape Hatches guide

### ISSUE THREAD

**Issue by SomayaB** [awsdocs/aws-cdk-guide#187]
Guide -> Concepts -> Escape Hatches -> Modifying the AWS CloudFormation Resource behind AWS Constructs

The first sentence of this section has a typo:

"If **an** Construct is missing a feature or you are trying to work around an issue, you can modify the CFN Resource that is encapsulated by the Construct."

**Comment by Jerry-AWS** [comment]
Fixed! Thanks for reporting it.
