### ISSUE TITLE
Instantiating a construct page , sample error . 

### ISSUE THREAD

**Issue by guan840912** [awsdocs/aws-cdk-guide#218]
### In aws cdk docs "Translating TypeScript AWS CDK code to other languages" Page 
Instantiating a construct `python sample` 
``` python 
# Instantiate Bucket with redirect_target, which has its own sub-properties
bucket = s3.Bucket(self, "MyBucket", redirect_target=s3.RedirectTarget(
            host_name="aws.amazon.com")) 
```
## Bucket 
```python 
classaws_cdk.aws_s3.Bucket(scope, id, *,bucket_name=None, ... , website_redirect=None, ...)
```
`redirect_target` in new cdk api docs , is `website_redirect`

**Comment by Jerry-AWS** [comment]
@guan840912 Thanks for catching that. I've updated it for all the languages. You should see this change on docs.aws.amazon.com in the next 24 hours.
