### ISSUE TITLE
Create Dash DocSet

### ISSUE THREAD

**Issue by iloveitaly** [awsdocs/aws-cdk-guide#219]
It would be amazing to have the CDK docs in Dash (local documentation manager):

https://kapeli.com/docsets

**Comment by Jerry-AWS** [comment]
@iloveitaly Are you looking for API reference, Dev Guide, both?

We do offer the Dev Guide in Kindle and PDF for your offline needs. I'm not sure that adding another offline format will become a priority for our build engineers, but you never know!

**Comment by iloveitaly** [comment]
@Jerry-AWS For the API reference. Right now, I can't find any offline zip file with the HTML for the cdk HTML API reference. Additionally, there's no search or filtering in the online API docs, which makes them hard to use.

Dash solves this problem and makes it really easy to search and navigate documentation without having to jump into the browser and jump around. Here's an example with the nodejs docs:

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/150855/84898362-5f481880-b064-11ea-8c62-a61707e1cbea.png">

It would be amazing if we could have this for CDK—full text search and method/symbol fuzzy matching would be incredibly helpful for developing in CDK.

**Comment by Jerry-AWS** [comment]
That does look really nice.

The CDK developers build the API Reference; I'll open an issue over in their repo. https://github.com/aws/aws-cdk

**Comment by Jerry-AWS** [comment]
I added this issue over there: https://github.com/aws/aws-cdk/issues/8617

So I'll close this one.
