### ISSUE TITLE
Remove build instructions in many places since the CDK does that for you now

### ISSUE THREAD

**Issue by jeznag** [awsdocs/aws-cdk-guide#220]
![image](https://user-images.githubusercontent.com/1034890/83847008-df11e100-a74e-11ea-9a9a-af91b02d19c2.png)

I don't understand why this is needed for typescript projects. I seem to be able to deploy/diff etc. without building.

**Comment by Jerry-AWS** [comment]
@jeznag Looks like that instruction is left over from an older version of the CDK. We're using `ts-node` now to run TypeScript apps, so the build step isn't technically necessary anymore. (Doesn't hurt anything, though.) I'll see about pulling it out at some point.

**Comment by Jerry-AWS** [comment]
In fact, how about now?
