### ISSUE TITLE
Code provided in  "Creating a code pipeline using the AWS CDK"  fails on CDK_Build action

### ISSUE THREAD

**Issue by AnatolyUA** [awsdocs/aws-cdk-guide#222]
I followed the example from "Creating a code pipeline using the AWS CDK" sample 
https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html
https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/codepipeline_example.md

but deployed pipeline fails on Build stage in CDK_Build action. I can't understand from example from what source is it supposed to get the code for the cdk project (for running `npm run cdk synth -- -o dist` command and getting `LambdaStack.template.json` file)

![Annotation 2020-06-17 085902](https://user-images.githubusercontent.com/1446703/84902126-667a2100-b07a-11ea-88cf-19233e5b5320.jpg)
[cdk_build-log.log](https://github.com/awsdocs/aws-cdk-guide/files/4792673/cdk_build-log.log)

**Comment by AnatolyUA** [comment]
this is the misleading comment: _"The AWS CDK code does not need to be in a repository."_ In the working example the lambda and cdk project were located in the same repo:
https://github.com/awsdocs/aws-cdk-guide/blob/cede996dfbd73d9e1bc59330ab10202bbc2e4e79/doc_source/codepipeline_example.md

**Comment by AnatolyUA** [comment]
and I don't think that 
```
npm run build, 
npm run cdk synth -- o dist
```

will work with any language except Typescript / Javascript

**Comment by Jerry-AWS** [comment]
I'm giving this example some attention right now. There were a lot of other things wrong with it earlier, which I've fixed, but I clearly still have some work to do. :-)
