### ISSUE TITLE
Issue in example code for Docker image asset deploy-time attributes

### ISSUE THREAD

**Issue by ali-tayebi** [awsdocs/aws-cdk-guide#223]
Could you please confirm the example code you have shown [here](https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/assets.md#deploy-time-attributes-example-1), for Docker image assets, is correct.

As `FromEcrRepository` API documentation says, the second argument is the image tag and not the image URL. For example, the C# code is as below:

```CSharp
taskDefinition.AddContainer("my-other-container", new ContainerDefinitionOptions
{
    Image = ContainerImage.FromEcrRepository(asset.Repository, asset.ImageUri)
});
```

So, it should be changed to:

```csharp
taskDefinition.AddContainer("my-other-container", new ContainerDefinitionOptions
{
    Image = ContainerImage.FromEcrRepository(asset.Repository, asset.ImageUri.Split(':').Last())
});
```

Happy to raise a PR if it makes sense

**Comment by Jerry-AWS** [comment]
@ali-tayebi Looks like you're right! This should be fixed on docs.aws.amazon.com in the next 24 hours.
