### ISSUE TITLE
SHIFT command in Windows does not remove arguments from %*

### ISSUE THREAD

**Issue by bravogolfgolf** [awsdocs/aws-cdk-guide#239]
"The shift command has no effect on the %* batch parameter." -- _see_ 4th bullet point in Remarks
[https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shift](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shift)

The Windows script 'cdk-deploy-to.bat' suggested on this page [https://docs.aws.amazon.com/cdk/latest/guide/environments.html](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) uses 'shift', but the result is not the same as the similar Linux/Mac OS X script 'cdk-deploy-to.sh'.

While is does set CDK_DEPLOY_ACCOUNT and CDK_DEPLOY_REGION properly. It also passes those values on and CDK DEPLOY interprets them as Stacks.

**Comment by Jerry-AWS** [comment]
Leave it to Microsoft, eh?

**Comment by Jerry-AWS** [comment]
Thanks for the PR to address this! I'm closing it now.
