### ISSUE TITLE
[@aws-cdk/aws-eks] How to get reference to CdkStackclusterKubectlProviderSecurityGroupXYZ?

### ISSUE THREAD

**Issue by acim** [awsdocs/aws-cdk-guide#256]
When I create EKS cluster using TS CDK, two security groups`with the following descriptions get created. 

```
EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.
```
and
```
EKS Control Plane Security Group
```
The first one can be referenced by cluster.clusterSecurityGroupId, where cluster is a constant referencing the created cluster itself. However, I can't find any reference to the second one. In AWS Console, the first one can be found under "Cluster security group" and the second one under "Additional security groups". I need to modify the second one, to add a rule.

**Comment by Jerry-AWS** [comment]
Hi @acim, I think this is more an API Reference issue (assuming there's some way to get the information you want) or else a feature request (if there's not). Accordingly, I've reposted it over in the CDK repo. https://github.com/aws/aws-cdk/issues/9780
