### ISSUE TITLE
Search for the API Reference docs

### ISSUE THREAD

**Issue by rehanvdm** [awsdocs/aws-cdk-guide#258]
Could we get a search for the API Reference docs? https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html

**Comment by Jerry-AWS** [comment]
This really belongs over in the CDK repo, as that development team owns the API reference. In fact, there's already an issue for adding search there. https://github.com/aws/aws-cdk/issues/5634. It's been there a while but maybe a few +1s will draw attention to it again. Closing this one. (I'm going to +1 that issue as well.)

**Comment by rehanvdm** [comment]
Thanks, did not know where the correct place is :)
