### ISSUE TITLE
Typos, mainly in code samples

### ISSUE THREAD

**Issue by max-webster** [awsdocs/aws-cdk-guide#277]
I'll include a sample URL to help locate the right source file / example more easily. Some of these are under a particular language tab, so not always amenable to find-in-page though.

consturcts - https://docs.aws.amazon.com/cdk/latest/guide/cli.html

defalut - https://docs.aws.amazon.com/cdk/latest/guide/get_env_var.html

acceess - https://docs.aws.amazon.com/cdk/latest/guide/resources.html

durinng - https://docs.aws.amazon.com/cdk/latest/guide/cdk_pipeline.html

boostrap - https://docs.aws.amazon.com/cdk/latest/guide/cdk_pipeline.html
- This one has propagated to or from various places. Not sure if any of these are fixable at the same time: https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation&searchQuery=%22boostrap%22

environmnt - https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html

evironment - https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html

falsy - https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-javascript.html

pepository -https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html

**Comment by Jerry-AWS** [comment]
"Falsy" is not a type; it's commonly used in dynamic languages for values that evaluate to false in a Boolean context. Truthy is is opposite. Fixed the rest.  :-)
