### ISSUE TITLE
cdk apiGateway-lambda docs missing

### ISSUE THREAD

**Issue by XiaolongLiuAtAutodesk** [awsdocs/aws-cdk-guide#280]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#lambda-based-request-authorizer

go into that page, 
There are examples for 
Lambda-based request authorizer
Lambda-based token authorizer
which is very nice, and there are hyperlink "You can find a full working example here", I clicked and got nothing.

getting return :
Looking for Something?
We're sorry. The web address you entered is not a functioning page on our site

**Comment by Jerry-AWS** [comment]
You're right! Thanks for catching this. It actually needs to be fixed over in the CDK repo since it's API Reference content. I've created a pull request:

https://github.com/aws/aws-cdk/pull/11384

I'll close this, since that PR should get merged soon.
