### ISSUE TITLE
CDK docs offer contradictory advice about Node.js version compatibility

### ISSUE THREAD

**Issue by mikeblas** [awsdocs/aws-cdk-guide#292]
The CDK Workshop says that any Node.js version greater than or equal to 10.3.0 will work:

https://cdkworkshop.com/15-prerequisites/300-nodejs.html

Other documentation contradicts that.  For example, this page has a "Prerequisites" section:

https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html

which says that that versions 13.0.0 thru 13.6.0 (inclusive?) are not compatible.

**Comment by Jerry-AWS** [comment]
Merging this with #291
