### ISSUE TITLE
IOT Core Rule not trigger lambda

### ISSUE THREAD

**Issue by tomcatvr** [awsdocs/aws-cdk-guide#295]
This code create a rule on IotCore which essentially use a lambda to log everything is published on the topic 'mytopic' 
CDK deploy the stack without error but the lambda is never called
To let the lambda be called I need to log on the console, select the rule -> Actions-> Edit and re select the lambda
        
```
Function lambdaFunction = Function.Builder.create(this, "logData")
                .code(Code.fromAsset("./asset/lambda-log-1.0-jar-with-dependencies.jar"))
                .handler("com.plussrl.devel.lamda.log.App")
                .runtime(Runtime.JAVA_11)
                .timeout(Duration.seconds(30))
                .memorySize(128)
                .build();

        CfnTopicRule.LambdaActionProperty lambdaActionProperty = CfnTopicRule.LambdaActionProperty
                .builder().functionArn(lambdaFunction.getFunctionArn()).build();

        CfnTopicRule.ActionProperty ap = CfnTopicRule.ActionProperty.builder().lambda(lambdaActionProperty).build();

        List<CfnTopicRule.ActionProperty> actions = new ArrayList<>();
        actions.add(ap);

        CfnTopicRule.TopicRulePayloadProperty topicRulePayloadProperty = CfnTopicRule.TopicRulePayloadProperty
                .builder()
                .actions(actions)
                .sql("SELECT * FROM 'mytopic'")
                .description("Log su lambda logData")
                .awsIotSqlVersion("2016-03-23")
                .ruleDisabled(false)
                .build();

        CfnTopicRule.Builder.create(this, "topicRule")
                .topicRulePayload(topicRulePayloadProperty)
                .ruleName("log_on_logData")
                .build();
    }
```

Step to reproduce
1) cdk deploy
2) test is not working publishing message (Iot Core-> test ->Publish topic: mytopic
3) nothing happens
4) edit the rule Iot Core-> Rules-> log_on_logData-> Actions-> Edit, select again IotCoreCdkStack-logDataXXX and then update
5) publish another message
6) wait a couple of seconds to see the log in cloudwatch

Sample project is in the attachment

[IOTCoreCDK.zip](https://github.com/awsdocs/aws-cdk-guide/files/5885892/IOTCoreCDK.zip)

**Comment by Jerry-AWS** [comment]
Hi @tomcatvr, please post this over at the CDK repo. This repo is for the CDK Developer Guide. Unfortunately since it's in a different organization, I can't just transfer it.

https://github.com/aws/aws-cdk/issues/new/choose

**Comment by tomcatvr** [comment]
Thanks, sorry. I'll put it in the repo you showed me
