### ISSUE TITLE
No contents in CDK reference page

### ISSUE THREAD

**Issue by hyogyunbang** [awsdocs/aws-cdk-guide#311]
I couldn't find a repository for CDK reference so I post this issue here. 

There isn't any contents in the following reference page.

https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ec2/cfnvpnconnection.html#aws_ec2_CfnVPNConnection

**Comment by Jerry-AWS** [comment]
The CDK API Reference is in the main CDK repo: https://github.com/aws/aws-cdk. I've re-filed it over there and am closing this issue.

https://github.com/aws/aws-cdk/issues/13065

That does look like a bug. I found CfnClientVpnEndpoint has the same issue.
