### ISSUE TITLE
"hello-cdk", not "HelloCdkStack", shows up in python walkthrough of "List the stacks in the app" when running "cdk ls"

### ISSUE THREAD

**Issue by nelsonjchen** [awsdocs/aws-cdk-guide#319]
https://github.com/awsdocs/aws-cdk-guide/blob/3cdafed83dde852f300221caa7613bed47dcda42/doc_source/hello_world.md#list-the-stacks-in-the-app

I'm not sure if this is something applicable to the other programming environments.

**Comment by Jerry-AWS** [comment]
@nelsonjchen Thanks for catching that. It appears to be a difference in the way the templates are set up for Python vs. the other languages. I've put in a pull request to change the Python template to be similar to the others.

https://github.com/aws/aws-cdk/pull/13480/files

**Comment by Jerry-AWS** [comment]
The aforementioned PR has been merged.

**Comment by nelsonjchen** [comment]
Thanks for looking into it!
