### ISSUE TITLE
Python example in Aspects Example is not valid Python

### ISSUE THREAD

**Issue by nelsonjchen** [awsdocs/aws-cdk-guide#321]
https://docs.aws.amazon.com/cdk/latest/guide/aspects.html#aspects_example

Python does not negate with `!`. It uses `not`.

**Comment by Jerry-AWS** [comment]
Right you are. Our code translation elves will be reprimanded. I've just fixed this; you should see it on docs.aws.amazon.com in the next 24 hours. 

Thanks for taking the time to report this. Your feedback helps us make the AWS CDK better for everyone. Keep it coming!
