### ISSUE TITLE
Add AWS CDK application best practices

### ISSUE THREAD

**Issue by maria-jackson** [awsdocs/aws-cdk-guide#339]
Can the content under "Code organization best practices" and "AWS CDK application best practices" in [Best practices for developing cloud application with aws cdk](https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/) be added to its own page similar to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html?

I'm totally awesome with a straight up copy and paste! But it would be really cool to have those in the actual documentation and maybe slightly shortened.

**Comment by AjkayAlan** [comment]
Bumping - I feel like a lot of the "CDK Best Practices" are spread between blog posts, github issues/comments/readmes, and some AWS docs. Having a single place for this would be beneficial.

**Comment by Jerry-AWS** [comment]
@maria-jackson That's a great idea. I've started with a slightly tidied up version of the blog post. The topic will be live on docs.aws.amazon.com within the next 24 hours. Please feel free to add new issues here for any additional content you'd like to see added.

The URL will be: https://docs.aws.amazon.com/cdk/latest/guide/best-practices.html

**Comment by AjkayAlan** [comment]
Looks like its live - Thanks!
