### ISSUE TITLE
Add AWS Solution Constructs Best Practices

### ISSUE THREAD

**Issue by AjkayAlan** [awsdocs/aws-cdk-guide#340]
Similar to #339 and related to #126, Can a "solution constructs" best practices be added to https://docs.aws.amazon.com/solutions/latest/constructs/welcome.html?

Ideally it would be similar to https://docs.aws.amazon.com/cdk/latest/guide/best-practices.html and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html. I would like it cover many of the main points in the [design guidelines](https://github.com/awslabs/aws-solutions-constructs/blob/main/DESIGN_GUIDELINES.md), but also cover some additional content if possible, such as:

- When should I create my own solution construct library versus use/contribute to aws-solution-constructs?
- What constitutes a solution construct versus a usecase?

**Comment by maria-jackson** [comment]
I love this! The solution construct vs use case is a very interesting area. (https://github.com/awslabs/aws-solutions-constructs/issues/131)

To me, 

-  a solution construct is something very simple (likely 2-3 resources)
- a use case could be reusable or not reusable, could live in a [construct-hub](https://github.com/cdklabs/construct-hub)

**Comment by maria-jackson** [comment]
I've also asked for some additional documentation from that team in https://github.com/awslabs/aws-solutions-constructs/issues/206.

**Comment by Jerry-AWS** [comment]
Yes, this is something you should ask the Solutions Constructs team for and that Github repo is probably the right place (or will get forwarded to the right place). We just do the CDK Developer Guide around these parts.  :-)  It's a great idea, though! Closing this issue.
