### ISSUE TITLE
Migrating to v2 link is broken 

### ISSUE THREAD

**Issue by danielconnor** [awsdocs/aws-cdk-guide#365]
The "Migrating to AWS CDK v2." link is broken on the [work-with-cdk-v2](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html) page. I guess the link [here](https://github.com/awsdocs/aws-cdk-guide/blob/main/doc_source/work-with-cdk-v2.md?plain=1#L7) should point to `../../v2/guide/migrating-v2.html` instead of `../../v2/migrating_v2.html`

**Comment by Jerry-AWS** [comment]
Fixed!
