### ISSUE TITLE
CDK Pipeline how to documentation contains error

### ISSUE THREAD

**Issue by TheFlexican** [awsdocs/aws-cdk-guide#371]
https://github.com/awsdocs/aws-cdk-guide/blob/main/v2/cdk_pipeline.md

Example code for lib/my-pipeline-app-stage.ts contains an error:

import Construct from constructs;

instead of

import { Construct } from 'constructs';

**Comment by Jerry-AWS** [comment]
thanks, fixed. You should see this on docs.aws.amazon.com within 24 hours
