### ISSUE TITLE
Home page: Link to full YAML is broken

### ISSUE THREAD

**Issue by SafaAlfulaij** [awsdocs/aws-cdk-guide#383]
Page: https://docs.aws.amazon.com/cdk/v2/guide/home.html
Section: Why use the AWS CDK?
After the code samples, the link to https://github.com/awsdocs/aws-cdk-guide/blob/main/doc_source/my_ecs_construct-stack.yaml is broken.

**Comment by Jerry-AWS** [comment]
Good catch. This link was broken when I moved the v1 files from /doc_source to /v1. Restored that YAML file under doc_source.
