### ISSUE TITLE
There is no IBucketProps in Code

### ISSUE THREAD

**Issue by ThomasSteinbach** [awsdocs/aws-cdk-guide#408]
The documentation talks about using `IBucketProps` as minimal configuration interface: https://github.com/awsdocs/aws-cdk-guide/blob/main/v2/work-with.md?plain=1#L115

However I haven't found `IBucketProps` in the code of AWS CDK v2. There is just a `BucketProps`.

Because the current documentation makes a distinction between `IBucketProps` and `BucketProps` itself, this doesn't look to me like just a typo. I think the documentation has to be updated here.

**Comment by Jerry-AWS** [comment]
we should use something else as an example here

**Comment by Jerry-AWS** [comment]
removed the example entirely for now, as I can't easily find a good example.
