### ISSUE TITLE
bootstrapping guide example is not Typescript friendly

### ISSUE THREAD

**Issue by rantoniuk** [awsdocs/aws-cdk-guide#419]
The [bootstrapping.md](https://github.com/awsdocs/aws-cdk-guide/blob/main/v2/bootstrapping.md) guide shows examples like this for TS:
```ts
new DefaultStackSynthesizer({
  // Name of the S3 bucket for file assets
  fileAssetsBucketName: 'cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}',
  bucketPrefix: '',
```

This is however not Typescript friendly and it (imho) should be expressed using backticks and Aws static class references:
```ts
new DefaultStackSynthesizer({
  // Name of the S3 bucket for file assets
  fileAssetsBucketName: `cdk-${DefaultStackSynthesizer.DEFAULT_QUALIFIER}-assets-${Aws.ACCOUNT_ID}-${Aws.REGION}`,
```

Happy to make a PR if you agree on the approach.

**Comment by Jerry-AWS** [comment]
The CDK Toolkit resolves those references, it's not something your app is responsible for. You could do it in TypeScript, as you show, but letting the CDK Toolkit do it works the same in all languages. I don't believe there's any reason to change this. Sorry!
