### ISSUE TITLE
"Multi-Language Support in the CDK" section needs work

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-cdk-guide#42]
Replaces this issue created by Doug-AWS on Apr 1 in the CDK repo: awslabs/aws-cdk#2136.

Original description: none

https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html

**Comment by Jerry-AWS** [comment]
Think this has been covered with the language-specific topics and the update to Translating TypeScript
