### ISSUE TITLE
"Contributing to the CDK" section needs work

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-cdk-guide#44]
Replaces this issue created by Doug-AWS on Apr 1 in the CDK repo: awslabs/aws-cdk#2134.

Original description: none

https://docs.aws.amazon.com/cdk/latest/guide/home.html#contributing

**Comment by Jerry-AWS** [comment]
This is covered by the Contribution Guidelines in the CDK repo; there's a link to it in Getting Started.
