### ISSUE TITLE
Create a "How-To Overcome the AWS CloudFormation 200 Resource Limit" section

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-cdk-guide#63]
Replaces this issue created by eladb on Jul 17, 2018 in the CDK repo: awslabs/aws-cdk#364.

Original description:

And/or describe in Troubleshooting topic in the docs?

**Comment by Jerry-AWS** [comment]
This has been described in Troubleshooting and the CDK now supports nested stacks.
