### ISSUE TITLE
Need "How-To Define a Nested Stack" section

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-cdk-guide#65]
Replaces this issue created by Doug-AWS on Jul 17, 2018 in the CDK repo: awslabs/aws-cdk#358.

Original description: none

**Comment by ccfife** [comment]
Nested stack support was released this week in CDK v1.12.0. 

https://github.com/aws/aws-cdk/pull/2821. 
https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudformation

**Comment by Jerry-AWS** [comment]
There's now an example in the Stacks topic
