### ISSUE TITLE
Document where the CDK "leaks"

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-cdk-guide#68]
Replaces this issue created by eladb on Jul 10, 2018 in the CDK repo: awslabs/aws-cdk#266.

Original description:

The CDK provides an abstraction over CloudFormation, but there are still cases where users need to "break the glass" and understand what's going on under the hood.

As a rule of thumb, we strive that the CDK's relationship to CloudFormation (or to any synthesized artifact) will "leak" in the situations that are similar to when compiled code "leaks" to the compiled program.

Here's an initial list:

- Cost
- Diagnostics
- Diff to deployed stack
- Resource attributes (that's actually a leak from the runtime)
- Resource Limits

**Comment by eladb** [comment]
This can be closed.
