### ISSUE TITLE
Did not recognize ~/.aws/config

### ISSUE THREAD

**Issue by kazumeat** [awsdocs/aws-cdk-guide#73]
https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/getting_started.md

I tried below command. But it had an error.
> For example, if the ~/.aws/config (Linux or Mac) or %USERPROFILE%\.aws\config (Windows) file contains the following 
> ENOENT: no such file or directory, open '/home/hoge/.aws/credentials'

I tried below command.
-> For example, if the ~/.aws/credentials (Linux or Mac) or %USERPROFILE%\.aws\credentials (Windows) file contains the following 

thanks.

**Comment by Doug-AWS** [comment]
If you use ```aws configure``` to configure your default credentials and region, the CLI stores your credentials in the file you cite, but less-sensitive information, such as your default region, in *config*, not *credentials*. See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html.
