### ISSUE TITLE
Property 'KmsManaged' does not exist

### ISSUE THREAD

**Issue by kazumeat** [awsdocs/aws-cdk-guide#74]
https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/getting_started.md

> encryption: s3.BucketEncryption.KmsManaged

-> KMS_MANAGED

**Comment by Doug-AWS** [comment]
Thanks, we had some late-breaking code changes that our doc tests missed. I'll fix this shortly, but you won't see the change until Wednesday as we have to wait until after the Amazon Prime days finish.

**Comment by Jerry-AWS** [comment]
@kazumeat We've made that fix on docs.aws.amazon.com, so I'm closing this issue. Thanks for reporting it! I will be pushing new Markdown files shortly.
