### ISSUE TITLE
Document that you need to specify a region and account in a stack when using the VPC construct

### ISSUE THREAD

**Issue by ccfife** [awsdocs/aws-cdk-guide#87]
Like this:

const app = new cdk.App();
new DemoStack(app, 'DemoStack', {
    env: { region: 'us-west-2', account: '033555032552' }
});

**Comment by skinny85** [comment]
A related issue, reported on Gitter:

-------------------------------

I define a load balancer and attempt to set accesslogs, however I keep getting errors: `Region is required to enable ELBv2 access logging`. Any idea as to why? Here's my code, very standard:

```typescript
const lb = new ApplicationLoadBalancer(this, 'LoadBalancer', {
            vpc,
            internetFacing: true
        });

lb.logAccessLogs(logsBucket, '/loadbalancer');
```
Any help is appreciated.

---------------------------------

The resolution here is the same (specifying `region` in `env` when creating the Stack).

**Comment by Jerry-AWS** [comment]
This probably needs to go in README for the EC2 construct.

**Comment by Jerry-AWS** [comment]
This seems to be well covered in the EC2 README, especially now that the Enivornements topic in the dev guide is more robust. I'll look into some of the other ones, like ec2-patterns, that involve availability zones.

**Comment by Jerry-AWS** [comment]
Re-verified that the E2C README covers the issue in sufficient detail. Added comment to logging method on ELBv2 ApplicationLoadBalancer about the issue as well. Did a quick scan of other code to see if any depended on environment but didn't find any. If anyone knows of any, let me know.
