### ISSUE TITLE
Logging topic (maybe general troubleshooting)

### ISSUE THREAD

**Issue by Jerry-AWS** [awsdocs/aws-cdk-guide#99]
Ref: https://github.com/aws/aws-cdk/issues/755

Could also cover other troubleshooting topics.

**Comment by rcollette** [comment]
It would be really helpful it these issues provided some link, search term or title for the documentation that gets added as a result of these issues.  I'm searching the dev guide for "logging" "log" and "logger" and I get nothing relevant.
